$(function(){
    $('input').click(function(){
        $.ajax({
            method:'GET',
            data:{name:'John'},
            url:'ajax.php',
            dataType:'html',
            success:function(reponse){
                alert(reponse);
            }
        })
    })
});